# Generated by Django 5.2.5 on 2026-05-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes_profile_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follower',
            new_name='followers',
        ),
    ]
